# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Dependency restore
      id: cache-restore
      uses: actions/cache@v4
      with:
        path: node_modules
        key: js-depend-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: npm ci
    - run: npm run build --if-present
      env:
        FM_CLIENT_ADMIN_API_URL : ${{ env.FM_CLIENT_ADMIN_API_URL }}
    - run: |
        ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP_FIRST }} -p ${{ secrets.VPS_SSH_PORT }} 'pm2 stop client-admin && cd ~/projects && git pull && npm install && pm2 start npm --name "client-admin" -- start'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        FM_CLIENT_ADMIN_API_URL : ${{ env.FM_CLIENT_ADMIN_API_URL }}
